server {
    listen 80;
    server_name _;

    gzip on;
    gzip_comp_level 5;
    gzip_min_length 256;
    gzip_proxied any;
    gzip_types
        text/plain
        text/css
        text/javascript
        application/javascript
        application/x-javascript
        application/json
        application/xml
        application/xml+rss
        application/vnd.ms-fontobject
        application/x-font-ttf
        font/opentype
        image/svg+xml;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }

    location ~* \.(?:html)$ {
        add_header Cache-Control "no-cache";
    }

    access_log /dev/stdout;
    error_log  /dev/stderr warn;
}

